language: go

go:
  - 1.8.x

env:
  - GO_ENV=test

services:
  - postgresql

before_script:
  - psql -c 'create database goshow_test;' -U postgres
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: github.com/thenomemac/goshow

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - go get -t $(go list ./... | grep -v /vendor/)

script: buffalo test
